baseURL = "https://oyjason.me/"
languageCode = "zh-cn"
title = "OYJason's Blog"
theme = "hugo-theme-stack"

[params]
    mainSections = ["post"]
    description = "å­¦ä¼šæ”¾å¥½ä»¥å‰çš„æ¸´æœ›"
    
    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "Loading quotes..."
        typeit = false

    [params.article]
        # å¦‚æœä½ åç»­è¦åœ¨æ–‡ç« é‡Œå†™ Boolean function analysis çš„å…¬å¼ï¼Œå¼€å¯è¿™ä¸ª
        math = true

    [params.footer]
        # è¿™é‡Œçš„ç‰ˆæƒå£°æ˜å¯ä»¥è‡ªå®šä¹‰
        copyright = "Â© 2026 OYJason"

# èœå•é…ç½®
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2