baseURL = "https://oyjason-blog.pages.dev/"
languageCode = "zh-cn"
title = "OYJason's Blog"
theme = "hugo-theme-stack"

[params]
    mainSections = ["post"]
    description = "OYJason's Blog"
    
    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "è®©è¿™ä¸ªä¸–ç•Œæˆä¸ºæƒ…ç»ªåƒåœ¾æ¡¶"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1