baseURL = "https://oyjason.me/"
languageCode = "zh-cn"
title = "OYJason's Blog"
theme = "hugo-theme-stack"

[params]
    mainSections = ["post"]
    author = "ä½ çš„åå­—"
    subtitle = "å­¦ä¼šæ”¾å¥½ä»¥å‰çš„æ¸´æœ›"
    avatar = "/images/avatar.png"

    [params.sidebar]
        emoji = "ğŸ¥"
        subtitle = "Loading quotes..."
        typeit = true

    [params.article]
        # å¦‚æœä½ åç»­è¦åœ¨æ–‡ç« é‡Œå†™ Boolean function analysis çš„å…¬å¼ï¼Œå¼€å¯è¿™ä¸ª
        math = true

    [params.footer]
        # è¿™é‡Œçš„ç‰ˆæƒå£°æ˜å¯ä»¥è‡ªå®šä¹‰
        copyright = "Â© 2026 OYJason"


# èœå•é…ç½®
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2


[params.widgets]
    # è¿™æ˜¯é¦–é¡µå’Œåˆ†ç±»é¡µçš„ä¾§è¾¹æ é…ç½®
    homepage = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]
    # è¿™æ˜¯æ–‡ç« è¯¦æƒ…é¡µçš„ä¾§è¾¹æ é…ç½®
    page = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]

# [[params.widgets]]
#     enabled = true
#     type = "profile"
#     avatar = "/images/PaperCrane.png"
    # author = "OYJason"
    # subtitle = "å°±å½“å…¨æ˜¯ä¸€åœºæ¢¦"
    # social = true
    
# [[params.widgets]]
#     enabled = true
#     type = "categories"
#     limit = 10
#     ordering = "count"
