baseURL = "https://oyjason.me/"
languageCode = "zh-cn"
title = "OYJason's Blog"
theme = "hugo-theme-stack"

[params]
    favicon = "/favicon.ico"
    mainSections = ["post"]
    author = "OYJason"
    description = "学会放好以前的渴望"

    [params.sidebar]
        # emoji = ""
        avatar = "/images/PaperCraneBlank.png"
        typeit = true

    [params.article]
        # 如果你后续要在文章里写 Boolean function analysis 的公式，开启这个
        math = true

    [params.footer]
        # 这里的版权声明可以自定义
        copyright = "© 2026 OYJason"



[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [menu.main.params]
        icon = "home"

[[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/enc_gallery/"
    weight = 2
    [menu.main.params]
        icon = "photo"


[[menu.main]]
    identifier = "encryptor"
    name = "Encryptor"
    url = "/encryptor/"
    weight = 3
    [menu.main.params]
        icon = "terminal"


[params.widgets]
    # 这是首页和分类页的侧边栏配置
    homepage = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]
    # 这是文章详情页的侧边栏配置
    page = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]
