baseURL = "https://oyjason.me/"
languageCode = "zh-cn"
title = "OYJason's Blog"
theme = "hugo-theme-stack"

[params]
    favicon = "/favicon.ico"
    mainSections = ["post"]
    author = "你的名字"
    description = "学会放好以前的渴望"

    [params.sidebar]
        # emoji = ""
        avatar = "/images/PaperCraneBlank.png"
        typeit = true

    [params.article]
        # 如果你后续要在文章里写 Boolean function analysis 的公式，开启这个
        math = true

    [params.footer]
        # 这里的版权声明可以自定义
        copyright = "© 2026 OYJason"


# 菜单配置
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 2


[params.widgets]
    # 这是首页和分类页的侧边栏配置
    homepage = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]
    # 这是文章详情页的侧边栏配置
    page = [
        # { type = "user", enabled = true, avatar = "/images/PaperCrane.png" },
        { type = "categories", enabled = true, limit = 10 }
    ]

# [[params.widgets]]
#     enabled = true
#     type = "profile"
#     avatar = "/images/PaperCrane.png"
    # author = "OYJason"
    # subtitle = "就当全是一场梦"
    # social = true
    
# [[params.widgets]]
#     enabled = true
#     type = "categories"
#     limit = 10
#     ordering = "count"
